import React,{useEffect,useState} from 'react';
import { Helmet } from 'react-helmet-async';
import { ArrowLeft, Award, Trophy } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Badge, Card, Spinner } from '../../components/ui';
import { useSettings } from '../../context/SettingsContext';
import { api } from '../../services/api';
import type { Achievement } from '../../types';
export function Achievements(){const {getSettingValue}=useSettings();const name=getSettingValue('general','school.name','Seven Star English Boarding School');const[items,setItems]=useState<Achievement[]>([]);const[loading,setLoading]=useState(true);useEffect(()=>{api.getPublishedAchievements({limit:100}).then(r=>setItems(r.data?.data?.achievements??r.data?.achievements??[])).catch(console.error).finally(()=>setLoading(false))},[]);return <><Helmet><title>Achievements | {name}</title><meta name="description" content={`Published achievements of ${name}.`}/></Helmet><div className="min-h-screen bg-white"><section className="bg-primary-700 text-white py-16"><div className="container-custom"><Link to="/" className="inline-flex items-center gap-2 text-primary-100 mb-6"><ArrowLeft className="w-4 h-4"/> Back to Home</Link><Badge variant="secondary" className="mb-4">Student Success</Badge><h1 className="font-heading text-4xl font-bold">Achievements</h1></div></section><section className="section"><div className="container-custom">{loading?<div className="flex justify-center py-16"><Spinner size="lg"/></div>:items.length===0?<Card className="text-center py-16"><Trophy className="w-12 h-12 mx-auto text-gray-300 mb-4"/><h2 className="text-xl font-semibold">No published achievements yet</h2></Card>:<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{items.map(a=><Card key={a._id} className="h-full"><div className="w-12 h-12 rounded-xl bg-primary-100 flex items-center justify-center"><Award className="w-6 h-6 text-primary-600"/></div><Badge variant="primary" className="mt-4">{a.category}</Badge><h2 className="font-heading text-xl font-semibold mt-2">{a.title}</h2><p className="text-gray-600 mt-2">{a.description}</p><p className="text-sm text-gray-500 mt-4">{a.eventDate?new Date(a.eventDate).toLocaleDateString():''}{a.position?` · ${a.position}`:''}{a.award?` · ${a.award}`:''}</p></Card>)}</div>}</div></section></div></>}
