import React,{useEffect,useState} from 'react';
import { Helmet } from 'react-helmet-async';
import { Activity as ActivityIcon, ArrowLeft, CalendarDays, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Badge, Card, Spinner } from '../../components/ui';
import { useSettings } from '../../context/SettingsContext';
import { api } from '../../services/api';
import type { Activity } from '../../types';
export function Activities(){const {getSettingValue}=useSettings();const name=getSettingValue('general','school.name','Seven Star English Boarding School');const[items,setItems]=useState<Activity[]>([]);const[loading,setLoading]=useState(true);useEffect(()=>{api.getPublishedActivities({limit:100}).then(r=>setItems(r.data?.data?.activities??r.data?.activities??[])).catch(console.error).finally(()=>setLoading(false))},[]);return <><Helmet><title>Activities | {name}</title><meta name="description" content={`Student activities and co-curricular programs published by ${name}.`}/></Helmet><div className="min-h-screen bg-gray-50"><section className="bg-primary-700 text-white py-16"><div className="container-custom"><Link to="/" className="inline-flex items-center gap-2 text-primary-100 mb-6"><ArrowLeft className="w-4 h-4"/> Back to Home</Link><h1 className="font-heading text-4xl font-bold">Activities</h1><p className="mt-4 text-primary-100">Co-curricular, sports, cultural and student activities published by the school.</p></div></section><section className="section"><div className="container-custom">{loading?<div className="flex justify-center py-16"><Spinner size="lg"/></div>:items.length===0?<Card className="text-center py-16"><ActivityIcon className="w-12 h-12 mx-auto text-gray-300 mb-4"/><h2 className="text-xl font-semibold">No published activities yet</h2></Card>:<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{items.map(a=><Card key={a._id} hover className="h-full"><Badge variant="primary">{a.category}</Badge><h2 className="font-heading text-xl font-semibold mt-3">{a.title}</h2><p className="text-gray-600 mt-2">{a.shortDescription||a.description}</p><div className="mt-4 space-y-2 text-sm text-gray-500"><span className="flex items-center gap-2"><CalendarDays className="w-4 h-4"/>{a.frequency}</span><span className="flex items-center gap-2"><Users className="w-4 h-4"/>{a.maxParticipants?`Up to ${a.maxParticipants} participants`:'Open to eligible students'}</span></div></Card>)}</div>}</div></section></div></>}
