import React,{useEffect,useState} from 'react';
import { Helmet } from 'react-helmet-async';
import { ArrowLeft, Image as ImageIcon, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Badge, Card, Spinner } from '../../components/ui';
import { useSettings } from '../../context/SettingsContext';
import { api } from '../../services/api';
import type { Gallery } from '../../types';
export function GalleryPage(){const {getSettingValue}=useSettings();const name=getSettingValue('general','school.name','Seven Star English Boarding School');const[items,setItems]=useState<Gallery[]>([]);const[loading,setLoading]=useState(true);const[selected,setSelected]=useState<string|null>(null);useEffect(()=>{api.getPublishedGalleries({limit:100}).then(r=>setItems(r.data?.data?.galleries??r.data?.galleries??[])).catch(console.error).finally(()=>setLoading(false))},[]);return <><Helmet><title>Gallery | {name}</title><meta name="description" content={`Photo gallery published by ${name}.`}/></Helmet><div className="min-h-screen bg-gray-50"><section className="bg-primary-700 text-white py-16"><div className="container-custom"><Link to="/" className="inline-flex items-center gap-2 text-primary-100 mb-6"><ArrowLeft className="w-4 h-4"/> Back to Home</Link><h1 className="font-heading text-4xl font-bold">Gallery</h1></div></section><section className="section"><div className="container-custom">{loading?<div className="flex justify-center py-16"><Spinner size="lg"/></div>:items.length===0?<Card className="text-center py-16"><ImageIcon className="w-12 h-12 mx-auto text-gray-300 mb-4"/><h2 className="text-xl font-semibold">No published gallery items yet</h2></Card>:<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{items.map(g=><Card key={g._id} hover className="p-0 overflow-hidden">{g.coverImage?<img src={g.coverImage} alt={g.title} className="w-full aspect-[4/3] object-cover" loading="lazy" onClick={()=>setSelected(g.coverImage||'')}/>:<div className="aspect-[4/3] flex items-center justify-center bg-gray-100"><ImageIcon className="w-12 h-12 text-gray-300"/></div>}<div className="p-5"><Badge variant="primary">{g.category}</Badge><h2 className="font-heading text-xl font-semibold mt-2">{g.title}</h2><p className="text-gray-600 text-sm mt-2">{g.description}</p><div className="grid grid-cols-4 gap-2 mt-4">{(g.images||[]).slice(0,8).map((img,i)=><img key={i} src={img.url} alt={img.alt||g.title} className="aspect-square object-cover rounded" loading="lazy" onClick={()=>setSelected(img.url)}/>)}</div></div></Card>)}</div>}</div></section></div>{selected&&<div className="fixed inset-0 z-50 bg-black/80 p-4 flex items-center justify-center" onClick={()=>setSelected(null)}><button className="absolute top-6 right-6 text-white" onClick={()=>setSelected(null)}><X className="w-8 h-8"/></button><img src={selected} alt="Gallery preview" className="max-h-[90vh] max-w-[95vw] object-contain"/></div>}</>}
